### ISSUE TITLE
What is the state of this project

### ISSUE THREAD

**Issue by Roald87** [amal029/st#1]
I'm currently writing a lexer for TwinCAT structured text in C# for my [TcBlack](https://github.com/Roald87/TcBlack) project. Then I came across your project and thought I could maybe use it as a basis to build the lexer in F#. I'm not familiar yet with F# or functional programming, so it is a bit hard to judge what the state of this code is. Does it work? Does it recognize all keywords already?

**Comment by amal029** [comment]
The project was abandoned. Not working, I think it has a grammar file,
but that's about all. The st grammar is huge, so it was not worth doing it. 


Roald87 ***@***.***> writes:

> I'm currently writing a lexer for TwinCAT structured text in C# for my TcBlack project. Then I came across
> your project and thought I could maybe use it as a basis to build the lexer in F#. I'm not familiar yet with F#
> or functional programming, so it is a bit hard to judge what the state of this code is. Does it work? Does it
> recognize all keywords already?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

-- 
Regards,

Avinash Malik
ECSE
University of Auckland,
NZ
